java.runtime.version=17

spring.datasource.url=jdbc:mysql://pwcspfbyl73eccbn.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/uaviuf2yqmwkp95c
spring.datasource.username=xk5qdvh2p2g7kf7e
spring.datasource.password=am2tljj5gx33v6vk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true