spring.application.name=cloudtestapp
server.port=8080

# Azure MySQL connection
spring.datasource.url=jdbc:mysql://pinto323mysql01.mysql.database.azure.com:3306/testapp_db?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=jpinto6
spring.datasource.password=Password123!

# JPA settings 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Prevent Spring from trying to run schema/data scripts automatically
spring.sql.init.mode=never